[package]
name = "avicoin"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4.3"
primitive-types = "0.13.1"
sha256 = "1.5.0"
rstest = "0.25.0"
anyhow = "1.0.98"
secp256k1 = { version = "0.31.1", features = ["rand", "std", "hashes"] }
